import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  schema: "./src/schema.graphql",
  documents: ["gql/autogenerated-operations/**/*.gql"],
  generates: {
    "gql/graphql.ts": {
      plugins: [
        "typescript",
        "typescript-operations",
        "typescript-generic-sdk",
      ],
      config: {
        rawRequest: false,
        scalars: {
          BigInt: "bigint|number",
          Date: "string",
        },
      },
    },
  },
};

export default config;
