query getAllOccupantProductsAllAgeRanges($session: Session!, $input: AllOccupantProductsAllAgeRangesInput!){
    getAllOccupantProductsAllAgeRanges(session: $session, input: $input){
        occupantProducts{
            categoryCode
            categoryLabel
            products{
                id
                code
                label
                webLabel
                originalLabel
                mandatory
                otherCode
                otherLabel
                price{
                    amount
                    currencyCode
                }
                priceWithoutDiscounts{
                    amount
                    currencyCode
                }
                quantityMax
                stock
                description
                isPackage
                isBase
                imagePath
                cmsCriterias{
                    code
                    label
                    value
                    servicesList{
                        id
                        login
                        customerCode
                        firstName
                        lastName
                        civility{
                            code
                            label
                        }
                        birthDate
                        serviceLanguage{
                            code
                            label
                            languageVars{
                                code
                                value
                            }
                        }
                        address{
                            streetName
                            addressComplementary1
                            addressComplementary2
                            postalLocality
                            zipCode
                            city
                            addressCountry{
                                code
                                label
                            }
                            phone1
                            phone2
                            fax
                            mail
                            latitude
                            longitude
                        }
                        criterias{
                            code
                            label
                            value
                            servicesList{
                                id
                                login
                                customerCode
                                firstName
                                lastName
                                birthDate
                                servicesList{
                                    id
                                    login
                                    customerCode
                                    firstName
                                    lastName
                                    birthDate
                                    fidelityPoints
                                    needValidation
                                    disabled
                                    defaultPartnerServiceDisabled
                                }
                                customerType{
                                    code
                                    label
                                }
                                relationshipObject{
                                    id
                                    label
                                }
                                clientType{
                                    id
                                    label
                                }
                                fidelityPoints
                                needValidation
                                disabled
                                defaultPartnerServiceDisabled
                            }
                            type
                            fileName
                            startDate
                            fileUrl
                        }
                        fidelityPoints
                        needValidation
                        disabled
                        defaultPartnerServiceDisabled
                    }
                    type
                    fileName
                    startDate
                    fileUrl
                }
                productCriterias{
                    code
                    label
                    value
                    servicesList{
                        id
                        login
                        customerCode
                        firstName
                        lastName
                        birthDate
                        fidelityPoints
                        needValidation
                        disabled
                        defaultPartnerServiceDisabled
                    }
                    type
                    fileName
                    startDate
                    fileUrl
                }
                subProducts{
                    id
                    code
                    label
                    webLabel
                    originalLabel
                    mandatory
                    otherCode
                    otherLabel
                    price{
                        amount
                        currencyCode
                    }
                    priceWithoutDiscounts{
                        amount
                        currencyCode
                    }
                    quantityMax
                    stock
                    description
                    isPackage
                    isBase
                    imagePath
                    cmsCriterias{
                        code
                        label
                        value
                        type
                        fileName
                        startDate
                        fileUrl
                    }
                    productCriterias{
                        code
                        label
                        value
                        type
                        fileName
                        startDate
                        fileUrl
                    }
                    subProducts{
                        id
                        code
                        label
                        webLabel
                        originalLabel
                        mandatory
                        otherCode
                        otherLabel
                        quantityMax
                        stock
                        description
                        isPackage
                        isBase
                        imagePath
                        linkedToMap
                        ageFrom
                        ageTo
                        distributionType
                        categoryCode
                        categoryLabel
                        occupantApplication
                        forCart
                        isLongStay
                    }
                    linkedToMap
                    ageFrom
                    ageTo
                    distributionType
                    categoryCode
                    categoryLabel
                    occupantApplication
                    forCart
                    isLongStay
                }
                linkedToMap
                ageFrom
                ageTo
                distributionType
                categoryCode
                categoryLabel
                occupantApplication
                forCart
                isLongStay
            }
        }
    }
}