query getCustomerPrivilegeCards($session: Session!){
    getCustomerPrivilegeCards(session: $session){
        privilegeCards{
            active
            bookingId
            label
            startDate
            endDate
            type
            service{
                id
                login
                customerCode
                firstName
                lastName
                civility{
                    code
                    label
                }
                birthDate
                serviceLanguage{
                    code
                    label
                    languageVars{
                        code
                        value
                    }
                }
                address{
                    streetName
                    addressComplementary1
                    addressComplementary2
                    postalLocality
                    zipCode
                    city
                    addressCountry{
                        code
                        label
                    }
                    phone1
                    phone2
                    fax
                    mail
                    latitude
                    longitude
                }
                criterias{
                    code
                    label
                    value
                    servicesList{
                        id
                        login
                        customerCode
                        firstName
                        lastName
                        civility{
                            code
                            label
                        }
                        birthDate
                        serviceLanguage{
                            code
                            label
                        }
                        address{
                            streetName
                            addressComplementary1
                            addressComplementary2
                            postalLocality
                            zipCode
                            city
                            phone1
                            phone2
                            fax
                            mail
                            latitude
                            longitude
                        }
                        criterias{
                            code
                            label
                            value
                            type
                            fileName
                            startDate
                            fileUrl
                        }
                        servicesList{
                            id
                            login
                            customerCode
                            firstName
                            lastName
                            birthDate
                            customerType{
                                code
                                label
                            }
                            relationshipObject{
                                id
                                label
                            }
                            clientType{
                                id
                                label
                            }
                            fidelityPoints
                            needValidation
                            disabled
                            defaultPartnerServiceDisabled
                        }
                        fidelityPoints
                        needValidation
                        disabled
                        defaultPartnerServiceDisabled
                    }
                    type
                    fileName
                    startDate
                    fileUrl
                }
                servicesList{
                    id
                    login
                    customerCode
                    firstName
                    lastName
                    birthDate
                    fidelityPoints
                    needValidation
                    disabled
                    defaultPartnerServiceDisabled
                }
                customerType{
                    code
                    label
                }
                relationshipObject{
                    id
                    label
                }
                clientType{
                    id
                    label
                }
                fidelityPoints
                needValidation
                disabled
                defaultPartnerServiceDisabled
            }
            points
        }
    }
}