query getCriteriaInformation($session: Session!, $input: CriteriaInformationInput){
    getCriteriaInformation(session: $session, input: $input){
        criteria{
            code
            label
            isChoice
            isFree
            isFile
            choiceList{
                code
                label
            }
            mandatory
        }
    }
}