query getCustomerDepositAccounts($session: Session!){
    getCustomerDepositAccounts(session: $session){
        customerDepositAccounts{
            id
            name
            propertyId
            type
            balance{
                amount
                currencyCode
            }
        }
    }
}