query getFerryProposals($session: Session!, $input: FerryProposalsInput!){
    getFerryProposals(session: $session, input: $input){
        proposals{
            id
            supplier{
                code
                label
            }
            outwardTrip{
                departurePort{
                    portName
                    label
                }
                arrivalPort{
                    portName
                    label
                }
                departureDate
                departureTime
                arrivalDate
                arrivalTime
                duration
                shipName
                coreTrip{
                    amount{
                        amount
                        currencyCode
                    }
                }
                vehicle{
                    vehicleType
                    mark
                    model
                    height
                    length
                    additionalHeight
                    additionalLength
                    registration
                }
                trailer{
                    trailerType
                    mark
                    model
                    height
                    length
                    registration
                    amount{
                        amount
                        currencyCode
                    }
                }
                accommodations{
                    code
                    label
                    occupancy
                    quantity
                    unitPrice{
                        amount
                        currencyCode
                    }
                    totalAmount{
                        amount
                        currencyCode
                    }
                }
                accommodationsAmount{
                    amount
                    currencyCode
                }
            }
            returnTrip{
                departurePort{
                    portName
                    label
                }
                arrivalPort{
                    portName
                    label
                }
                departureDate
                departureTime
                arrivalDate
                arrivalTime
                duration
                shipName
                vehicle{
                    vehicleType
                    mark
                    model
                    height
                    length
                    additionalHeight
                    additionalLength
                    registration
                }
                trailer{
                    trailerType
                    mark
                    model
                    height
                    length
                    registration
                }
                accommodations{
                    code
                    label
                    occupancy
                    quantity
                }
                accommodationsAmount{
                    amount
                    currencyCode
                }
            }
            totalAmount{
                amount
                currencyCode
            }
            isFlexibleFare
            tariff{
                tariffBand
                tariffType
            }
        }
        warningList
        canChooseRoundTripProposals
    }
}