query getFerryAddonCategories($session: Session!){
    getFerryAddonCategories(session: $session){
        addonCategories{
            code
            label
            size
            type
        }
    }
}