query getFerryCrossings($session: Session!, $input: FerryCrossingsInput){
    getFerryCrossings(session: $session, input: $input){
        crossings{
            departurePort{
                portName
                label
            }
            arrivalPort{
                portName
                label
            }
        }
    }
}