query getFidelityLogs($session: Session!){
    getFidelityLogs(session: $session){
        fidelityLogs{
            numResa
            fidelityPoints
            date
            label
        }
    }
}