query getFerryVehicleCategories($session: Session!){
    getFerryVehicleCategories(session: $session){
        vehicleCategories{
            code
            label
            isCar
        }
    }
}