query getMapSelectorData($session: Session!, $input: MapSelectorDataInput){
    getMapSelectorData(session: $session, input: $input){
        mapSelectorData{
            fileSystemName
            imageHeight
            imageWidth
            listUhOnMap{
                id
                label
                color
                roomTypeCode
                coordinates{
                    lat
                    lng
                }
                textColor
                strokeColor
                stayGuiid
                stayRoomIndex
                shape
            }
            listUhSelected{
                id
                label
                color
                roomTypeCode
                coordinates{
                    lat
                    lng
                }
                textColor
                strokeColor
                stayGuiid
                stayRoomIndex
                shape
            }
            listUhDisabled{
                id
                label
                color
                roomTypeCode
                coordinates{
                    lat
                    lng
                }
                textColor
                strokeColor
                stayGuiid
                stayRoomIndex
                shape
            }
            stayMapInfos{
                stayGuiid
                hasNoAvailableRoom
                listStayRoomGuiid
            }
            zoom
            opacity
        }
    }
}