query getNeobookingTranslations($session: Session!, $input: NeobookingTranslationsInput){
    getNeobookingTranslations(session: $session, input: $input){
        translations{
            code
            label
            languageVars{
                code
                value
            }
        }
    }
}