query getOwnerLeases($session: Session!){
    getOwnerLeases(session: $session){
        leases{
            id
            etabId
            etabLabel
            periods{
                id
                lots{
                    id
                    label
                    roomNumbers
                }
            }
        }
    }
}