query getPaymentMethods($session: Session!){
    getPaymentMethods(session: $session){
        paymentMethod{
            automaticPaymentCode
            virtualPaymentCode
            paymentMethodOption{
                code
                label
            }
            automaticPaymentMethodOption{
                code
                label
            }
        }
    }
}