query getPaymentPlans($session: Session!, $input: PaymentPlansInput){
    getPaymentPlans(session: $session, input: $input){
        paymentPlans{
            code
            label
            isDefault
            cmsCriterias{
                code
                label
                value
                servicesList{
                    id
                    login
                    customerCode
                    firstName
                    lastName
                    civility{
                        code
                        label
                    }
                    birthDate
                    serviceLanguage{
                        code
                        label
                        languageVars{
                            code
                            value
                        }
                    }
                    address{
                        streetName
                        addressComplementary1
                        addressComplementary2
                        postalLocality
                        zipCode
                        city
                        addressCountry{
                            code
                            label
                        }
                        phone1
                        phone2
                        fax
                        mail
                        latitude
                        longitude
                    }
                    criterias{
                        code
                        label
                        value
                        servicesList{
                            id
                            login
                            customerCode
                            firstName
                            lastName
                            birthDate
                            servicesList{
                                id
                                login
                                customerCode
                                firstName
                                lastName
                                birthDate
                                customerType{
                                    code
                                    label
                                }
                                relationshipObject{
                                    id
                                    label
                                }
                                clientType{
                                    id
                                    label
                                }
                                fidelityPoints
                                needValidation
                                disabled
                                defaultPartnerServiceDisabled
                            }
                            fidelityPoints
                            needValidation
                            disabled
                            defaultPartnerServiceDisabled
                        }
                        type
                        fileName
                        startDate
                        fileUrl
                    }
                    fidelityPoints
                    needValidation
                    disabled
                    defaultPartnerServiceDisabled
                }
                type
                fileName
                startDate
                fileUrl
            }
            occupantPaymentDues{
                id
                guiid
                code
                amount{
                    amount
                    currencyCode
                }
                receivedAmount{
                    amount
                    currencyCode
                }
                remainingAmount{
                    amount
                    currencyCode
                }
                date
                payments{
                    id
                    guiid
                    amount{
                        amount
                        currencyCode
                    }
                    date
                    paymentModeLabel
                    voucherCode
                }
                label
                type
                creditCard{
                    guiid
                    maskedPan
                    cardholderName
                }
            }
            partnerPaymentDues{
                id
                guiid
                code
                amount{
                    amount
                    currencyCode
                }
                receivedAmount{
                    amount
                    currencyCode
                }
                remainingAmount{
                    amount
                    currencyCode
                }
                date
                payments{
                    id
                    guiid
                    date
                    paymentModeLabel
                    voucherCode
                }
                label
                type
                creditCard{
                    guiid
                    maskedPan
                    cardholderName
                }
            }
            paymentMethod{
                automaticPaymentCode
                virtualPaymentCode
                paymentMethodOption{
                    code
                    label
                }
                automaticPaymentMethodOption{
                    code
                    label
                }
            }
            cartItemID
        }
    }
}