query getPartnerCustomers($session: Session!){
    getPartnerCustomers(session: $session){
        customers{
            civility
            name
            firstName
            externalCode
            email
            disabled
            customerCode
        }
    }
}