query getProposalsByKeys($session: Session!, $input: ProposalsByKeysInput!){
    getProposalsByKeys(session: $session, input: $input){
        proposals{
            proposalKey
            propertyId
            startDate
            endDate
            nbDays
            productOption{
                code
                label
            }
            priceWithoutDiscount{
                amount
                currencyCode
            }
            roomFeaturesValues{
                code
                label
                value
                servicesList{
                    id
                    login
                    customerCode
                    firstName
                    lastName
                    civility{
                        code
                        label
                    }
                    birthDate
                    serviceLanguage{
                        code
                        label
                        languageVars{
                            code
                            value
                        }
                    }
                    address{
                        streetName
                        addressComplementary1
                        addressComplementary2
                        postalLocality
                        zipCode
                        city
                        addressCountry{
                            code
                            label
                        }
                        phone1
                        phone2
                        fax
                        mail
                        latitude
                        longitude
                    }
                    criterias{
                        code
                        label
                        value
                        servicesList{
                            id
                            login
                            customerCode
                            firstName
                            lastName
                            birthDate
                            servicesList{
                                id
                                login
                                customerCode
                                firstName
                                lastName
                                birthDate
                                customerType{
                                    code
                                    label
                                }
                                relationshipObject{
                                    id
                                    label
                                }
                                clientType{
                                    id
                                    label
                                }
                                fidelityPoints
                                needValidation
                                disabled
                                defaultPartnerServiceDisabled
                            }
                            fidelityPoints
                            needValidation
                            disabled
                            defaultPartnerServiceDisabled
                        }
                        type
                        fileName
                        startDate
                        fileUrl
                    }
                    fidelityPoints
                    needValidation
                    disabled
                    defaultPartnerServiceDisabled
                }
                type
                fileName
                startDate
                fileUrl
            }
            stock
            imagePath
            price{
                amount
                currencyCode
            }
            baseProductPrice{
                amount
                currencyCode
            }
            discountInfo
            distribution{
                roomTypes{
                    code
                    label
                    webLabel
                    cmsCriterias{
                        code
                        label
                        value
                        servicesList{
                            id
                            login
                            customerCode
                            firstName
                            lastName
                            birthDate
                            fidelityPoints
                            needValidation
                            disabled
                            defaultPartnerServiceDisabled
                        }
                        type
                        fileName
                        startDate
                        fileUrl
                    }
                    roomFeatures{
                        code
                        label
                        value
                        servicesList{
                            id
                            login
                            customerCode
                            firstName
                            lastName
                            birthDate
                            fidelityPoints
                            needValidation
                            disabled
                            defaultPartnerServiceDisabled
                        }
                        type
                        fileName
                        startDate
                        fileUrl
                    }
                    description
                    paxMax
                    quantity
                    categoryCode
                    categoryLabel
                    pax
                    propertyId
                }
                roomNumbers
            }
            isCounterProposal
            isAlternativeProposal
            lineItems{
                id
                guiid
                label
                preReserved
                quantity
                discounts{
                    label
                    specificLabel
                    quantity
                    price{
                        amount
                        currencyCode
                    }
                    voucherCode
                    documentLabel
                    discountCode
                    fidelityPoints
                }
                totalAmount{
                    amount
                    currencyCode
                }
                product{
                    id
                    code
                    label
                    webLabel
                    originalLabel
                    mandatory
                    otherCode
                    otherLabel
                    price{
                        amount
                        currencyCode
                    }
                    priceWithoutDiscounts{
                        amount
                        currencyCode
                    }
                    quantityMax
                    stock
                    description
                    isPackage
                    isBase
                    imagePath
                    cmsCriterias{
                        code
                        label
                        value
                        type
                        fileName
                        startDate
                        fileUrl
                    }
                    productCriterias{
                        code
                        label
                        value
                        servicesList{
                            id
                            login
                            customerCode
                            firstName
                            lastName
                            birthDate
                            fidelityPoints
                            needValidation
                            disabled
                            defaultPartnerServiceDisabled
                        }
                        type
                        fileName
                        startDate
                        fileUrl
                    }
                    subProducts{
                        id
                        code
                        label
                        webLabel
                        originalLabel
                        mandatory
                        otherCode
                        otherLabel
                        price{
                            amount
                            currencyCode
                        }
                        priceWithoutDiscounts{
                            amount
                            currencyCode
                        }
                        quantityMax
                        stock
                        description
                        isPackage
                        isBase
                        imagePath
                        cmsCriterias{
                            code
                            label
                            value
                            type
                            fileName
                            startDate
                            fileUrl
                        }
                        productCriterias{
                            code
                            label
                            value
                            type
                            fileName
                            startDate
                            fileUrl
                        }
                        subProducts{
                            id
                            code
                            label
                            webLabel
                            originalLabel
                            mandatory
                            otherCode
                            otherLabel
                            quantityMax
                            stock
                            description
                            isPackage
                            isBase
                            imagePath
                            linkedToMap
                            ageFrom
                            ageTo
                            distributionType
                            categoryCode
                            categoryLabel
                            occupantApplication
                            forCart
                            isLongStay
                        }
                        linkedToMap
                        ageFrom
                        ageTo
                        distributionType
                        categoryCode
                        categoryLabel
                        occupantApplication
                        forCart
                        isLongStay
                    }
                    linkedToMap
                    ageFrom
                    ageTo
                    distributionType
                    categoryCode
                    categoryLabel
                    occupantApplication
                    forCart
                    isLongStay
                }
                totalAmountWithoutDiscount{
                    amount
                    currencyCode
                }
                isSkiset
                ferryBooking{
                    resFerryId
                    bookingRef
                    status
                    sendStatus
                    supplier{
                        code
                        label
                    }
                    passengers{
                        index
                        passengerTypeCode
                        lastName
                        firstName
                        birthDate
                        civility{
                            code
                            label
                        }
                        nationality
                        passport
                        passportExpiry
                        availablePassengerTypes{
                            code
                            label
                        }
                    }
                    outwardTrip{
                        departurePort{
                            portName
                            label
                        }
                        arrivalPort{
                            portName
                            label
                        }
                        departureDate
                        departureTime
                        arrivalDate
                        arrivalTime
                        duration
                        shipName
                        coreTrip{
                            amount{
                                amount
                                currencyCode
                            }
                        }
                        vehicle{
                            vehicleType
                            mark
                            model
                            height
                            length
                            additionalHeight
                            additionalLength
                            registration
                        }
                        trailer{
                            trailerType
                            mark
                            model
                            height
                            length
                            registration
                            amount{
                                amount
                                currencyCode
                            }
                        }
                        accommodations{
                            code
                            label
                            occupancy
                            quantity
                            unitPrice{
                                amount
                                currencyCode
                            }
                            totalAmount{
                                amount
                                currencyCode
                            }
                        }
                        accommodationsAmount{
                            amount
                            currencyCode
                        }
                    }
                    returnTrip{
                        departurePort{
                            portName
                            label
                        }
                        arrivalPort{
                            portName
                            label
                        }
                        departureDate
                        departureTime
                        arrivalDate
                        arrivalTime
                        duration
                        shipName
                        vehicle{
                            vehicleType
                            mark
                            model
                            height
                            length
                            additionalHeight
                            additionalLength
                            registration
                        }
                        trailer{
                            trailerType
                            mark
                            model
                            height
                            length
                            registration
                        }
                        accommodations{
                            code
                            label
                            occupancy
                            quantity
                        }
                        accommodationsAmount{
                            amount
                            currencyCode
                        }
                    }
                    contact{
                        email
                        phone
                    }
                    totalAmount{
                        amount
                        currencyCode
                    }
                    passportMandatory
                }
                duration
                criterias{
                    code
                    label
                    value
                    type
                    fileName
                    startDate
                    fileUrl
                }
            }
            isMonthPrice
        }
    }
}