query getRoomTypes($session: Session!, $input: RoomTypesInput){
    getRoomTypes(session: $session, input: $input){
        roomTypeList{
            code
            label
            webLabel
            cmsCriterias{
                code
                label
                value
                servicesList{
                    id
                    login
                    customerCode
                    firstName
                    lastName
                    civility{
                        code
                        label
                    }
                    birthDate
                    serviceLanguage{
                        code
                        label
                        languageVars{
                            code
                            value
                        }
                    }
                    address{
                        streetName
                        addressComplementary1
                        addressComplementary2
                        postalLocality
                        zipCode
                        city
                        addressCountry{
                            code
                            label
                        }
                        phone1
                        phone2
                        fax
                        mail
                        latitude
                        longitude
                    }
                    criterias{
                        code
                        label
                        value
                        servicesList{
                            id
                            login
                            customerCode
                            firstName
                            lastName
                            birthDate
                            servicesList{
                                id
                                login
                                customerCode
                                firstName
                                lastName
                                birthDate
                                customerType{
                                    code
                                    label
                                }
                                relationshipObject{
                                    id
                                    label
                                }
                                clientType{
                                    id
                                    label
                                }
                                fidelityPoints
                                needValidation
                                disabled
                                defaultPartnerServiceDisabled
                            }
                            fidelityPoints
                            needValidation
                            disabled
                            defaultPartnerServiceDisabled
                        }
                        type
                        fileName
                        startDate
                        fileUrl
                    }
                    fidelityPoints
                    needValidation
                    disabled
                    defaultPartnerServiceDisabled
                }
                type
                fileName
                startDate
                fileUrl
            }
            roomFeatures{
                code
                label
                value
                servicesList{
                    id
                    login
                    customerCode
                    firstName
                    lastName
                    birthDate
                    fidelityPoints
                    needValidation
                    disabled
                    defaultPartnerServiceDisabled
                }
                type
                fileName
                startDate
                fileUrl
            }
            description
            paxMax
            quantity
            categoryCode
            categoryLabel
            pax
            propertyId
        }
    }
}