query getSkisetMeasurements($session: Session!){
    getSkisetMeasurements(session: $session){
        measurements{
            calfwidths{
                id
                value
            }
            footwidths{
                id
                value
            }
            headsizes{
                id
                value
            }
            heights{
                id
                value
            }
            shoesizes{
                id
                value
            }
            unit
            weights{
                id
                value
            }
        }
    }
}